export type WidgetLang = "fr" | "en";

export const STRINGS = {
  fr: {
    welcome: {
      eyebrow: "Diagnostic gratuit · 30 secondes",
      title: "Es-tu vraiment couvert pour ton voyage ?",
      subtitle:
        "Réponds à 5 questions et découvre si ta carte bancaire, ta mutuelle et ta sécu suffisent vraiment.",
      cta: "Commencer le diagnostic",
      privacy: "Aucune donnée personnelle collectée. Aucun email demandé.",
      poweredBy: "Propulsé par",
    },
    progress: { step: "Étape", of: "sur" },
    nav: { back: "Retour", next: "Continuer", skip: "Passer", finish: "Voir mon diagnostic" },
    q1: {
      title: "Tu pars où ?",
      subtitle: "Choisis ta destination principale.",
      placeholder: "Ex. Bali, Canada, Maroc…",
      popular: "Destinations populaires",
    },
    q2: {
      title: "Combien de temps ?",
      subtitle: "Sélectionne la durée approximative.",
      days: "jours",
      shortLabel: "Court séjour (1–7 j)",
      mediumLabel: "Vacances (1–4 sem.)",
      longLabel: "Long séjour (1–6 mois)",
      yearLabel: "1 an et +",
    },
    q3: {
      title: "Tu voyages avec ?",
      subtitle: "Indique qui voyage avec toi.",
      alone: "Seul·e",
      partner: "Conjoint·e",
      kids: "Enfant(s)",
      friends: "Ami(e)s / famille",
      ageTitle: "Tranche d'âge du voyageur principal",
    },
    q4: {
      title: "As-tu déjà une couverture ?",
      subtitle: "Coche tout ce qui s'applique. C'est ce qu'on va vérifier.",
      visa_premier: "Carte Visa Premier",
      mastercard_gold: "Carte Mastercard Gold",
      barclays: "Barclays Travel Pack",
      none_card: "Aucune carte premium",
      mutuelle_yes: "Une mutuelle santé",
      mutuelle_no: "Pas de mutuelle",
      ss_fr: "Sécurité sociale (France)",
      ss_uk: "NHS / GHIC (UK)",
    },
    q5: {
      title: "Une particularité ?",
      subtitle: "Coche si l'un de ces points concerne ton voyage.",
      winter: "Sports d'hiver / ski",
      extreme: "Sports extrêmes / plongée / trek",
      cruise: "Croisière",
      cancel: "Tu veux pouvoir annuler ton voyage si pépin",
      none: "Rien de tout ça",
    },
    analyzing: {
      title: "Analyse en cours…",
      lines: [
        "On vérifie tes plafonds de frais médicaux",
        "On compare avec les standards des compagnies d'assurance",
        "On identifie tes éventuels trous de couverture",
      ],
    },
    result: {
      title: "Ton diagnostic de couverture",
      score: "Score de couverture",
      criticalGaps: "trou(s) critique(s)",
      warningGaps: "point(s) à surveiller",
      ctaTitle: "La solution HelloSafe",
      cta: "Voir le tarif HelloSafe →",
      restart: "Refaire le diagnostic",
      excellent: "Couverture excellente",
      good: "Couverture correcte",
      partial: "Couverture partielle",
      insufficient: "Couverture insuffisante",
      from: "À partir de",
      perDay: "/ jour",
      whatYouHave: "Ce que tu as",
      whatYouMiss: "Ce qui manque",
      hellosafeAnswer: "Réponse HelloSafe",
    },
    severity: {
      critical: "Critique",
      warning: "Attention",
      info: "OK",
    },
    common: {
      poweredBy: "Diagnostic gratuit propulsé par HelloSafe",
    },
  },
  en: {
    welcome: {
      eyebrow: "Free check · 30 seconds",
      title: "Are you really covered for your trip?",
      subtitle:
        "Answer 5 questions to see whether your bank card, your top-up plan and your social security really cover you.",
      cta: "Start my check",
      privacy: "No personal data collected. No email asked.",
      poweredBy: "Powered by",
    },
    progress: { step: "Step", of: "of" },
    nav: { back: "Back", next: "Continue", skip: "Skip", finish: "See my report" },
    q1: {
      title: "Where are you going?",
      subtitle: "Pick your main destination.",
      placeholder: "e.g. Bali, Canada, Morocco…",
      popular: "Popular destinations",
    },
    q2: {
      title: "How long?",
      subtitle: "Pick the approximate duration.",
      days: "days",
      shortLabel: "Short trip (1–7 d)",
      mediumLabel: "Holiday (1–4 wk)",
      longLabel: "Long stay (1–6 m)",
      yearLabel: "1 year and more",
    },
    q3: {
      title: "Who's travelling?",
      subtitle: "Tell us who's coming along.",
      alone: "Solo",
      partner: "Partner",
      kids: "Kids",
      friends: "Friends / family",
      ageTitle: "Age range of the main traveller",
    },
    q4: {
      title: "Do you already have any cover?",
      subtitle: "Tick all that apply. We'll check what they actually cover.",
      visa_premier: "Visa Premier card",
      mastercard_gold: "Mastercard Gold",
      barclays: "Barclays Travel Pack",
      none_card: "No premium card",
      mutuelle_yes: "Private health top-up",
      mutuelle_no: "No top-up",
      ss_fr: "French Sécu",
      ss_uk: "NHS / GHIC (UK)",
    },
    q5: {
      title: "Anything specific?",
      subtitle: "Tick if any of these apply to your trip.",
      winter: "Winter sports / skiing",
      extreme: "Extreme sports / diving / trek",
      cruise: "Cruise",
      cancel: "I want to be able to cancel if needed",
      none: "None of these",
    },
    analyzing: {
      title: "Analysing…",
      lines: [
        "Checking your medical-cost ceilings",
        "Comparing to insurance-industry baselines",
        "Spotting any cover gaps",
      ],
    },
    result: {
      title: "Your cover report",
      score: "Cover score",
      criticalGaps: "critical gap(s)",
      warningGaps: "warning(s)",
      ctaTitle: "The HelloSafe answer",
      cta: "See HelloSafe price →",
      restart: "Restart the check",
      excellent: "Excellent cover",
      good: "Decent cover",
      partial: "Partial cover",
      insufficient: "Insufficient cover",
      from: "From",
      perDay: "/ day",
      whatYouHave: "What you have",
      whatYouMiss: "What's missing",
      hellosafeAnswer: "HelloSafe answer",
    },
    severity: {
      critical: "Critical",
      warning: "Heads up",
      info: "OK",
    },
    common: {
      poweredBy: "Free cover check by HelloSafe",
    },
  },
} as const;

export type Strings = (typeof STRINGS)["fr"];
